from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (FormView, LoginView, LogoutView,
                                       TemplateView)
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import RedirectView

from discordbot.forms import WFSettingsForm
from discordbot.models import DiscordUser, WFSettings
from main.forms import (DiscordProfileForm, DiscordTokenForm,
                        MainAuthenticationForm, MainUserCreationForm)


class HomeView(TemplateView):
    template_name = 'home.html'


class MainLoginView(LoginView):
    authentication_form = MainAuthenticationForm
    redirect_authenticated_user = True


class MainLogoutView(LogoutView):
    next_page = 'main:home'


class SignupView(FormView):
    form_class = MainUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('main:home')

    def get_success_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return super().get_success_url()

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, TemplateView):
    """
    General profile view with two forms - general settings for DiscordUser and
    Warframe settings. For now it requires User to be linked with DiscordUser
    instance.
    """
    login_url = '/login/'
    template_name = 'profile.html'
    success_messages = {
        'DiscordProfileForm': 'Profile settings has been updated',
        'WFSettingsForm': 'Warframe alerts settings has been updated',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        discord_user = getattr(self.request.user, 'discorduser', None)
        discord_social = self.request.user.socialaccount_set.filter(
            provider='discord').first()
        # if not discord_user:
        #     if discord_social:
        #         uid = int(discord_social.uid)
        #         _existing_discord_user = DiscordUser.objects.filter(id=uid).first()
        #         if _existing_discord_user:
        #             self.request.user.discorduser = _existing_discord_user
        #             if not hasattr(_existing_discord_user, 'wf_settings'):
        #                 _existing_discord_user.wf_settings = WFSettings.objects.create()
        #             self.request.user.save()
        #             messages.add_message(
        #                 request=self.request,
        #                 level=messages.SUCCESS,
        #                 message='Successfully autolinked with existing DiscordUser instance'
        #             )
        #             discord_user = _existing_discord_user
        context.update({
            'discorduser': discord_user,
            'discord_social': discord_social,
            'blizzardsocial': self.request.user.socialaccount_set.filter(provider='battlenet').first(),
        })
        # if not any([context.get(x) for x in ('profile_form', 'wf_settings_form')]):
        #     context.update({
        #         'profile_form': DiscordProfileForm(
        #             user=self.request.user,
        #             instance=getattr(self.request.user, 'discorduser', None)
        #         ),
        #         # 'wf_settings_form': WFSettingsForm(
        #         #     instance=self.request.user.discorduser.wf_settings
        #         # ),
        #     })
        return context

    def post(self, request):
        profile_form = DiscordProfileForm(
            data=request.POST, user=request.user,
            instance=request.user.discorduser
        )
        wf_form = WFSettingsForm(
            data=request.POST,
            instance=request.user.discorduser.wf_settings,
            request=request
        )
        for form in (profile_form, wf_form):
            if form.has_changed() and form.is_valid():
                form.save(user=request.user)
                messages.add_message(
                    request=request,
                    level=messages.SUCCESS,
                    message=self.success_messages[form.__class__.__name__]
                )
        return self.render_to_response({
            'profile_form': profile_form,
            'wf_settings_form': wf_form,
        })


class DiscordLinkView(FormView):
    """
    View for linking current authenticated user with existing DiscordUser by
    passing token generated by Discord bot into form. In case user is already
    linked, he will be redirected to profile page. Token could also be passed
    as query parameter and User will be linked and redirected automatically
    """
    form_class = DiscordTokenForm
    template_name = 'discord_link.html'

    def get_success_url(self):
        return reverse_lazy('main:profile')

    def _autolink(self, token):
        class_form = self.get_form_class()
        form = class_form(data={'token': token})
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('main:login')
        if hasattr(request.user, 'discorduser'):
            return redirect('main:profile')
        if request.GET.get('token'):
            return self._autolink(request.GET.get('token'))
        if request.user.socialaccount_set.exists():
            discord_account = request.user.socialaccount_set.filter(
                provider='discord').first()
            if discord_account:
                uid = int(discord_account.uid)
                discord_user = DiscordUser.objects.filter(id=uid).first()
                request.user.discorduser = discord_user
                if not hasattr(discord_user, 'wf_settings'):
                    discord_user.wf_settings = WFSettings.objects.create()
                request.user.save()
                messages.add_message(
                    request=request,
                    level=messages.SUCCESS,
                    message='Successfully autolinked with existing DiscordUser instance'
                )
                return redirect('main:profile')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.link_discord_profile(self.request.user)
        return super().form_valid(form)
