# Generated by Django 4.2.18 on 2025-08-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlycemicData",
            fields=[
                ("time", models.BigIntegerField(primary_key=True, serialize=False)),
                ("glycemic", models.FloatField()),
            ],
            options={
                "db_table": "glycemic_data",
            },
        ),
    ]
