RESOURCES = {
    'Nitain Extract (Resource)' : 'nitain_extract',
    'Orokin Cell (Resource)' : 'orokin_cell',
    'Orokin Cell Resource' : 'orokin_cell',
    'Orokin Reactor (Blueprint)' : 'orokin_reactor_bp',
    'Orokin Reactor (Item)' : 'orokin_reactor_bp',
    'Orokin Catalyst Blueprint' : 'orokin_catalyst_bp',
    'Orokin Catalyst (Blueprint)' : 'orokin_catalyst_bp',
    'Orokin Catalyst (Item)' : 'orokin_catalyst_bp',
    'Tellurium (Resource)' : 'tellurium',
    'Forma Blueprint' : 'forma_bp',
    'Forma (Item)' : 'forma_bp',
    'Exilus Adapter Blueprint' : 'exilus_bp',
    'Exilus Adapter (Blueprint)' : 'exilus_bp',
    'Exilus Adapter' : 'exilus_ap',
    'Exilus Adaptor' : 'exilus_ap',
    'Exilus Adaptor (Item)' : 'exilus_ap',
    'Exilus Adapter (Item)' : 'exilus_ap',
    'kavat' : 'kavat',
    '5x Kavat Genetic Code (Resource)' : 'kavat',
    '10x Kavat Genetic Code (Resource)' : 'kavat',
    'Corrosive Projection (Aura)', 'corrosive',
    'corrosive' : 'corrosive',
}
