# Generated by Django 2.2.28 on 2022-11-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discordbot', '0027_delete_mixpollentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gem',
                'verbose_name_plural': 'Gems',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='PoeInfo',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('class_name', models.TextField(max_length=30)),
                ('class_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ascendancy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('experience', models.BigIntegerField(blank=True, null=True)),
                ('gems', models.ManyToManyField(to='poe.ActiveGem')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.League')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordUser')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
    ]
