# Generated by Django 2.2.28 on 2023-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
