# Generated by Django 4.2.3 on 2023-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poe", "0002_character_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="combined_dps",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="es",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="life",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activegem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
