# Generated by Django 4.2.3 on 2023-08-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poe", "0003_character_combined_dps_character_es_character_life_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="experience_trend",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, ""),
                    (1, "Player has more experience since last update"),
                    (2, "Player has less experience since last update"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="es",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Energy Shield"
            ),
        ),
    ]
