# Generated by Django 4.2.3 on 2023-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poe", "0004_character_experience_trend_alter_character_es"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("icon", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="character",
            name="experience_trend",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No changes"),
                    (1, "Player has more experience since last update"),
                    (2, "Player has less experience since last update"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="items",
            field=models.ManyToManyField(blank=True, to="poe.item"),
        ),
    ]
