# Generated by Django 4.2.3 on 2023-08-16 14:21

from django.db import migrations, models
import django.utils.timezone
from datetime import timedelta


def convert_experience_to_last_level_modified(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Character = apps.get_model('poe', 'Character')
    League = apps.get_model('poe', 'League')

    league_ids = set(League.objects.values_list('id', flat=True))
    new_date = django.utils.timezone.now() - timedelta(weeks=4)

    for _id in league_ids:
        qs = Character.objects.using(db_alias).filter(league_id=_id).order_by('-experience')
        for idx, character in enumerate(qs):
            character.level_modified_at = new_date + timedelta(seconds=idx)
            character.save(update_fields=['level_modified_at'])


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("poe", "0005_item_alter_character_experience_trend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="level_modified_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=convert_experience_to_last_level_modified,
            reverse_code=backwards_func
        )
    ]
