# Generated by Django 2.0.2 on 2018-02-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('victims', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('actions2', models.TextField(blank=True, null=True)),
                ('places', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brawl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CachedNicknames',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cached_nicknames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gachi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'gachi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('url', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.TextField(blank=True, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.TextField(max_length=40, unique=True)),
                ('steam_id', models.IntegerField(blank=True, null=True)),
                ('blizzard_id', models.TextField(blank=True, null=True)),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('mod_group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discord_users',
            },
        ),
        migrations.CreateModel(
            name='Imgur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(db_column='pID')),
                ('url', models.URLField(unique=True)),
                ('date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imgur',
            },
        ),
        migrations.CreateModel(
            name='Wisdom',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(db_column='pID', default=0)),
                ('text', models.TextField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordUser', verbose_name='discord user')),
            ],
            options={
                'db_table': 'wisdom',
            },
        ),
    ]
