# Generated by Django 2.0.2 on 2018-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='bnet_token',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
