# Generated by Django 2.0.2 on 2018-02-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0002_discorduser_poe_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoeCharacter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('league', models.TextField(max_length=30)),
                ('ascendancy', models.TextField(max_length=30)),
                ('level', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordUser')),
            ],
        ),
    ]
