# Generated by Django 2.0.2 on 2018-08-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0002_discorduser_bnet_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='bnet_token',
        ),
    ]
