# Generated by Django 2.0.2 on 2018-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0004_auto_20180220_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='poe_profile',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
