# Generated by Django 2.2 on 2019-04-25 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0005_auto_20190426_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.IntegerField(blank=True, help_text='Required. 18 characters, digits only.', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,18}$')], verbose_name='Discord ID'),
        ),
    ]
