# Generated by Django 2.2.1 on 2019-05-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0003_remove_discorduser_bnet_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduser',
            options={'permissions': [('can_update_ladder', 'Can start ladder update'), ('can_add_wisdoms', 'Can add wisdoms')], 'verbose_name_plural': 'Discord Users'},
        ),
    ]
