# Generated by Django 2.2.2 on 2019-07-27 15:43

import django.db.models.deletion
from django.db import migrations, models


def create_counters(apps, schema_editor):
    CounterGroup = apps.get_model("discordbot", "CounterGroup")
    group = CounterGroup.objects.create(
        name='bodycount',
        title='Counters for Zang'
    )
    Counter = apps.get_model("discordbot", "Counter")
    Counter.objects.bulk_create([
        Counter(name='bodycount_killed',
                value_description='Killed by Zang',
                title='Killed by Zang',
                group_id=1
                ),
        Counter(name='bodycount_saved',
                value_description='Saved by Zang',
                title='Saved by Zang',
                group_id=1
                ),
    ])


def remove_counters(apps, schema_editor):
    CounterGroup = apps.get_model("discordbot", "CounterGroup")
    Counter = apps.get_model("discordbot", "Counter")
    Counter.objects.all().delete()
    CounterGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0007_auto_20190526_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('latest_counter_id', models.PositiveIntegerField(
                    blank=True, null=True)),
                ('latest_counter_streak', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('flavor_text', models.TextField(blank=True)),
                ('value_description', models.TextField()),
                ('value', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='counters', to='discordbot.CounterGroup')),
            ],
        ),
        migrations.RunPython(create_counters, reverse_code=remove_counters)
    ]
