# Generated by Django 2.0.2 on 2018-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0007_auto_20180220_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='poe_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poecharacter',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
