# Generated by Django 2.0.2 on 2018-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0008_auto_20180220_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poecharacter',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
