# Generated by Django 2.0.2 on 2018-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0009_auto_20180220_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poecharacter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
