# Generated by Django 2.0.2 on 2018-02-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0010_auto_20180220_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poecharacter',
            name='profile',
        ),
        migrations.DeleteModel(
            name='PoeCharacter',
        ),
    ]
