# Generated by Django 2.2.8 on 2019-12-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0010_markovtext_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfsettings',
            name='exilus_ap',
            field=models.BooleanField(default=False, verbose_name='Exilus Adapter'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='forma_bp',
            field=models.BooleanField(default=False, verbose_name='Forma Blueprint'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='kavat',
            field=models.BooleanField(default=False, verbose_name='Kavat Genetic Code'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='nitain_extract',
            field=models.BooleanField(default=False, verbose_name='Nitain Extract'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='orokin_catalyst_bp',
            field=models.BooleanField(default=False, verbose_name='Orokin Catalyst (Blueprint)'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='orokin_cell',
            field=models.BooleanField(default=False, verbose_name='Orokin Cell'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='orokin_reactor_bp',
            field=models.BooleanField(default=False, verbose_name='Orokin Reactor (Blueprint)'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='tellurium',
            field=models.BooleanField(default=False, verbose_name='Tellurium'),
        ),
    ]
