# Generated by Django 2.2.8 on 2019-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0011_auto_20191203_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfalert',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='wfsettings',
            name='kavat',
        ),
        migrations.RemoveField(
            model_name='wfsettings',
            name='nitain_extract',
        ),
        migrations.RemoveField(
            model_name='wfsettings',
            name='orokin_cell',
        ),
        migrations.RemoveField(
            model_name='wfsettings',
            name='tellurium',
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='dera',
            field=models.BooleanField(default=False, verbose_name='Dera Vandal'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='detonite_injector',
            field=models.BooleanField(default=False, verbose_name='Detonite Injector'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='fieldron',
            field=models.BooleanField(default=False, verbose_name='Fieldron'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='karak',
            field=models.BooleanField(default=False, verbose_name='Karak Wraith'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='latron',
            field=models.BooleanField(default=False, verbose_name='Latron Wraith'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='mutagen_mass',
            field=models.BooleanField(default=False, verbose_name='Mutagen Mass'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='mutalist_nav',
            field=models.BooleanField(default=False, verbose_name='Mutalist Alad V Nav Coordinate'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='snipetron',
            field=models.BooleanField(default=False, verbose_name='Snipetron Vandal'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='strun',
            field=models.BooleanField(default=False, verbose_name='Strun Wraith'),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='twin_vipers',
            field=models.BooleanField(default=False, verbose_name='Twin Vipers Wraith'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='forma_bp',
            field=models.BooleanField(default=False, verbose_name='Forma'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='orokin_catalyst_bp',
            field=models.BooleanField(default=False, verbose_name='Orokin Catalyst'),
        ),
        migrations.AlterField(
            model_name='wfsettings',
            name='orokin_reactor_bp',
            field=models.BooleanField(default=False, verbose_name='Orokin Reactor'),
        ),
    ]
