# Generated by Django 2.0.2 on 2018-03-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0011_auto_20180221_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gachi',
            options={},
        ),
    ]
