# Generated by Django 2.2.7 on 2020-01-31 18:23

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    link = apps.get_model('discordbot', 'DiscordLink')
    if not link.objects.filter(key='corona').exists():
        link.objects.using(db_alias).create(
            key='corona',
            url=''
        )


def backwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    link = apps.get_model('discordbot', 'DiscordLink')
    link.objects.filter(key='corona').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0012_auto_20191206_1453'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
