# Generated by Django 2.2.7 on 2020-01-31 18:23

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    link = apps.get_model('discordbot', 'DiscordLink')
    if not link.objects.filter(key='corona').exists():
        link.objects.using(db_alias).create(
            key='corona',
            url='https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/1/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outStatistics=%5B%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22Confirmed%22%2C%22outStatisticFieldName%22%3A%22value%22%7D%5D&cacheHint=true'
        )


def backwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    link = apps.get_model('discordbot', 'DiscordLink')
    link.objects.filter(key='corona').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0012_auto_20191206_1453'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
