# Generated by Django 2.0.2 on 2018-03-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0013_discordsettings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discordsettings',
            table='discord_settings',
        ),
    ]
