# Generated by Django 2.2.7 on 2020-01-31 18:23

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    link = apps.get_model('discordbot', 'DiscordLink')
    link.objects.using(db_alias).create(key='corona_deaths', url='')
    link.objects.using(db_alias).create(key='corona_recovered', url='')


def backwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    link = apps.get_model('discordbot', 'DiscordLink')
    link.objects.using(db_alias).filter(key='corona_deaths').delete()
    link.objects.using(db_alias).filter(key='corona_recovered').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0013_coronavirus'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
