# Generated by Django 2.0.2 on 2018-03-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0014_auto_20180321_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('url', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'discord_links',
            },
        ),
        migrations.AlterModelOptions(
            name='discordsettings',
            options={'verbose_name_plural': 'Discord Settings'},
        ),
    ]
