# Generated by Django 2.2.7 on 2020-02-17 17:14

from django.db import migrations, models


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    link = apps.get_model('discordbot', 'DiscordLink')
    keys = ['corona_deaths', 'corona_recovered', 'corona']
    link.objects.using(db_alias).filter(key__in=keys).delete()


def backwards(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0014_auto_20200131_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.RunPython(forwards, backwards)
    ]
