# Generated by Django 2.2.8 on 2020-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0015_coronareport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markovtext',
            name='key',
            field=models.IntegerField(help_text='Discord Channel ID', unique=True),
        ),
    ]
