# Generated by Django 2.0.2 on 2018-03-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0015_auto_20180321_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordlink',
            name='url',
            field=models.URLField(),
        ),
    ]
