# Generated by Django 2.2.10 on 2020-05-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0016_auto_20200430_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MixEvent',
        ),
    ]
