# Generated by Django 2.0.2 on 2018-03-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0016_auto_20180321_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordsettings',
            name='value',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
