# Generated by Django 2.2.10 on 2020-05-09 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0015_coronareport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('checksum', models.CharField(editable=False, max_length=16, null=True)),
                ('pid', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='mix')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordUser', verbose_name='discord user')),
            ],
            options={
                'verbose_name': 'Mix Image',
                'verbose_name_plural': 'Mix Images',
            },
        ),
    ]
