# Generated by Django 2.0.2 on 2018-03-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0017_auto_20180321_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedNickname',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discord_users_cache',
            },
        ),
    ]
