# Generated by Django 2.2.10 on 2020-05-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0018_miximage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordPicture',
        ),
    ]
