# Generated by Django 2.0.2 on 2018-03-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0018_cachednickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachednickname',
            name='date',
        ),
    ]
