# Generated by Django 2.2.10 on 2020-09-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0019_delete_discordpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='wf_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.WFSettings'),
        ),
    ]
