# Generated by Django 2.0.2 on 2018-03-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0019_remove_cachednickname_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='admin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mod_group',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
