# Generated by Django 2.0.2 on 2018-03-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0020_auto_20180322_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedNickname',
        ),
    ]
