# Generated by Django 2.2.10 on 2020-09-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0020_auto_20200906_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='blizzard_id',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='steam_id',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='token',
        ),
        migrations.AlterField(
            model_name='miximage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordUser', verbose_name='discord user'),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordUser', verbose_name='discord user'),
        ),
    ]
