# Generated by Django 2.2.10 on 2020-10-04 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0021_auto_20200908_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigIntegerField(
                blank=True,
                help_text='Required. 18 characters, digits only.',
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[django.core.validators.RegexValidator('^\\d{1,18}$')],
                verbose_name='Discord ID'
            ),
        ),
        migrations.AlterField(
            model_name='markovtext',
            name='key',
            field=models.BigIntegerField(help_text='Discord Channel ID', unique=True),
        ),
        migrations.AlterField(
            model_name='miximage',
            name='checksum',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
