# Generated by Django 2.0.2 on 2018-03-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0021_delete_cachednickname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wisdom',
            table='discord_wisdoms',
        ),
    ]
