# Generated by Django 2.0.2 on 2018-03-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0022_auto_20180322_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imgur',
            new_name='DiscordPicture',
        ),
        migrations.AlterModelTable(
            name='discordpicture',
            table='discord_pictures',
        ),
    ]
