# Generated by Django 2.2.10 on 2020-10-18 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0023_auto_20201018_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisdom',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wisdom',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wisdom',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
