# Generated by Django 2.0.2 on 2018-03-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0023_auto_20180322_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordpicture',
            name='pid',
            field=models.IntegerField(db_column='pID', default=0),
        ),
        migrations.AlterModelTable(
            name='brawl',
            table='discord_brawl',
        ),
    ]
