# Generated by Django 2.0.2 on 2018-03-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0024_auto_20180322_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brawl',
            options={},
        ),
    ]
