# Generated by Django 2.2.18 on 2021-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0025_auto_20201231_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miximage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
