# Generated by Django 2.2.18 on 2021-10-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0026_auto_20210924_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MixPollEntry',
        ),
    ]
