# Generated by Django 2.0.2 on 2018-03-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0026_auto_20180322_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brawl',
        ),
    ]
