# Generated by Django 2.2.28 on 2023-01-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0027_delete_mixpollentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordlink',
            old_name='url',
            new_name='value',
        ),
    ]
