# Generated by Django 2.0.2 on 2018-03-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0028_brawl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brawl',
            old_name='actions',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='brawl',
            old_name='actions2',
            new_name='action2',
        ),
        migrations.RenameField(
            model_name='brawl',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brawl',
            old_name='places',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='brawl',
            old_name='tools',
            new_name='tool',
        ),
        migrations.RenameField(
            model_name='brawl',
            old_name='victims',
            new_name='victim',
        ),
    ]
