# Generated by Django 2.2.28 on 2023-02-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0028_auto_20230123_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brawl',
        ),
        migrations.DeleteModel(
            name='Gachi',
        ),
        migrations.DeleteModel(
            name='WFAlert',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='wf_settings',
        ),
        migrations.DeleteModel(
            name='WFSettings',
        ),
    ]
