# Generated by Django 2.2.28 on 2023-02-07 17:24

from django.db import migrations, models


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    user = apps.get_model('discordbot', 'DiscordUser')
    user.objects.using(db_alias).filter(poe_profile='').update(poe_profile=None)


def backwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    user = apps.get_model('discordbot', 'DiscordUser')
    user.objects.using(db_alias).filter(poe_profile__isnull=True).update(poe_profile='')


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0029_auto_20230207_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='poe_profile',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='PoE Account'),
        ),
        migrations.RunPython(forwards, backwards)
    ]
