# Generated by Django 2.0.2 on 2018-03-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0029_auto_20180322_1216'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gachi',
            table='discord_gachi',
        ),
    ]
