# Generated by Django 2.0.2 on 2018-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0030_auto_20180322_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gachi',
            name='pid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
