# Generated by Django 4.2.3 on 2023-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0031_alter_discordlink_id_alter_discordsettings_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="miximage",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
