# Generated by Django 2.0.2 on 2018-03-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0031_auto_20180322_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='display_name',
            field=models.TextField(max_length=40),
        ),
    ]
