# Generated by Django 2.0.2 on 2018-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0033_auto_20180326_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='test_bool',
            field=models.BooleanField(default=False),
        ),
    ]
