# Generated by Django 2.0.2 on 2018-03-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0036_remove_discorduser_test_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='blizzard_id',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Blizzard Tag'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='display_name',
            field=models.TextField(help_text='Current discord display name', max_length=40, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.IntegerField(blank=True, help_text='Required. 18 characters, digits only.', max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='Discord ID'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mod_group',
            field=models.BooleanField(default=False, verbose_name='Chat mod'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='poe_profile',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='PoE Account'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='steam_id',
            field=models.IntegerField(blank=True, default=None, max_length=17, null=True, verbose_name='Steam ID'),
        ),
    ]
