# Generated by Django 2.0.2 on 2018-03-30 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0037_auto_20180330_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(blank=True, help_text='Required. 18 characters, digits only.', max_length=18, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,18}$')], verbose_name='Discord ID'),
        ),
    ]
