# Generated by Django 2.0.2 on 2018-03-30 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0038_auto_20180330_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='steam_id',
            field=models.CharField(blank=True, default=None, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,17}$')], verbose_name='Steam ID'),
        ),
    ]
