# Generated by Django 2.0.2 on 2018-03-30 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0039_auto_20180330_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='admin',
            field=models.BooleanField(default=False, help_text='User can execute @admin commands'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='blizzard_id',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Blizzard Tag'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mod_group',
            field=models.BooleanField(default=False, help_text='User can execute @mod commands', verbose_name='Moderator'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='poe_profile',
            field=models.TextField(blank=True, default='', null=True, verbose_name='PoE Account'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='steam_id',
            field=models.CharField(blank=True, default=None, help_text='17 characters, digits only.', max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,17}$')], verbose_name='Steam ID'),
        ),
    ]
