# Generated by Django 2.0.2 on 2018-04-01 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0041_auto_20180330_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordlink',
            options={'verbose_name_plural': 'Discord Links'},
        ),
        migrations.AlterModelOptions(
            name='discorduser',
            options={'verbose_name_plural': 'Discord Users'},
        ),
        migrations.AlterField(
            model_name='discordlink',
            name='key',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discordsettings',
            name='key',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discordsettings',
            name='value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='blizzard_id',
            field=models.TextField(blank=True, default='', help_text='Example: Username-0000', verbose_name='Blizzard Tag'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='poe_profile',
            field=models.TextField(blank=True, default='', verbose_name='PoE Account'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='steam_id',
            field=models.CharField(blank=True, default='', help_text='17 characters, digits only.', max_length=17, validators=[django.core.validators.RegexValidator('^\\d{1,17}$')], verbose_name='Steam ID'),
        ),
    ]
