# Generated by Django 2.0.2 on 2018-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0042_auto_20180401_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordsettings',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
