# Generated by Django 2.0.2 on 2018-04-16 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discordbot', '0043_auto_20180401_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='token',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
