# Generated by Django 2.0.2 on 2018-04-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0044_auto_20180416_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='token',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
