# Generated by Django 2.0.2 on 2018-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0045_auto_20180416_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='is_linked',
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
