# Generated by Django 2.0.2 on 2018-04-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0046_auto_20180416_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='avatar_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
