# Generated by Django 2.0.2 on 2018-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0047_discorduser_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFAlert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('announced', models.BooleanField(default=False)),
                ('place', models.TextField()),
                ('mission_time', models.IntegerField()),
                ('reward_credits', models.TextField()),
                ('reward_resource', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discord_alerts',
            },
        ),
    ]
