# Generated by Django 2.0.2 on 2018-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0048_wfalert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfalert',
            old_name='place',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='wfalert',
            name='mission_time',
        ),
        migrations.RemoveField(
            model_name='wfalert',
            name='reward_credits',
        ),
        migrations.AlterField(
            model_name='wfalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
