# Generated by Django 2.0.2 on 2018-04-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0050_discorduser_warframe_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='warframe_resources',
        ),
    ]
