# Generated by Django 2.0.2 on 2018-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0051_remove_discorduser_warframe_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitain', models.BooleanField(default=False)),
                ('discorduser', models.ManyToManyField(to='discordbot.DiscordUser')),
            ],
        ),
    ]
