# Generated by Django 2.0.2 on 2018-04-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0052_wfsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfsettings',
            name='discorduser',
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='discorduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordUser'),
        ),
    ]
