# Generated by Django 2.0.2 on 2018-04-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0056_auto_20180423_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfsettings',
            old_name='nitain',
            new_name='nitain_extract',
        ),
    ]
