# Generated by Django 2.0.2 on 2018-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0057_auto_20180424_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfsettings',
            name='orokin_catalyst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='orokin_cell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='orokin_reactor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='tellurium',
            field=models.BooleanField(default=False),
        ),
    ]
