# Generated by Django 2.0.2 on 2018-04-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('discordbot', '0058_auto_20180424_0207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wfsettings',
            table='discord_wf_settings',
        ),
    ]
