# Generated by Django 2.0.2 on 2018-04-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0059_auto_20180424_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfalert',
            old_name='reward_resource',
            new_name='keywords',
        ),
    ]
