# Generated by Django 2.0.2 on 2018-04-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0060_auto_20180424_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfsettings',
            name='forma_bp',
            field=models.BooleanField(default=False),
        ),
    ]
