# Generated by Django 2.0.2 on 2018-04-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0061_wfsettings_forma_bp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wfalert',
            options={'verbose_name': 'Warframe Alert', 'verbose_name_plural': 'Warframe Alerts'},
        ),
        migrations.RenameField(
            model_name='wfsettings',
            old_name='orokin_catalyst',
            new_name='exilus_ap',
        ),
        migrations.RenameField(
            model_name='wfsettings',
            old_name='orokin_reactor',
            new_name='exilus_bp',
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='orokin_catalyst_bp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wfsettings',
            name='orokin_reactor_bp',
            field=models.BooleanField(default=False),
        ),
    ]
