# Generated by Django 2.0.2 on 2018-04-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0062_auto_20180424_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfsettings',
            name='kavat',
            field=models.BooleanField(default=False),
        ),
    ]
