# Generated by Django 2.0.2 on 2018-05-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0065_auto_20180517_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfsettings',
            name='corrosive',
        ),
    ]
