# Generated by Django 2.0.2 on 2018-08-19 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PVPBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('weekly_played', models.IntegerField(blank=True, null=True)),
                ('weekly_won', models.IntegerField(blank=True, null=True)),
                ('weekly_lost', models.IntegerField(blank=True, null=True)),
                ('season_played', models.IntegerField(blank=True, null=True)),
                ('season_won', models.IntegerField(blank=True, null=True)),
                ('season_lost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wow_brackets',
                'verbose_name_plural': 'PVP Brackets',
                'verbose_name': 'PVP Bracket',
            },
        ),
        migrations.CreateModel(
            name='WOWAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bnet_id', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wow_accounts',
                'verbose_name_plural': 'WOW Accounts',
                'verbose_name': 'WOW Account',
            },
        ),
        migrations.CreateModel(
            name='WOWCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('realm', models.CharField(blank=True, max_length=50, null=True)),
                ('battlegroup', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('character_class', models.IntegerField(blank=True, null=True)),
                ('race', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('achievement_points', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField()),
                ('last_modified', models.IntegerField(blank=True, null=True)),
                ('track', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowstats.WOWAccount')),
            ],
            options={
                'db_table': 'wow_characters',
                'verbose_name_plural': 'WOW Characters',
                'verbose_name': 'WOW Character',
            },
        ),
        migrations.CreateModel(
            name='WOWStatSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorable_kills', models.IntegerField(blank=True, null=True)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('arena_2v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_2v2', to='wowstats.PVPBracket')),
                ('arena_3v3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_3v3', to='wowstats.PVPBracket')),
                ('arena_rbg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_rbg', to='wowstats.PVPBracket')),
                ('arena_skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_skirmish', to='wowstats.PVPBracket')),
                ('arena_unknown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_unknown', to='wowstats.PVPBracket')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowstats.WOWCharacter')),
            ],
            options={
                'db_table': 'wow_stats',
            },
        ),
    ]
