# Generated by Django 2.0.2 on 2018-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0002_auto_20180819_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowsettings',
            name='public_view',
            field=models.BooleanField(default=True),
        ),
    ]
