# Generated by Django 2.0.2 on 2018-08-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0003_wowsettings_public_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowstatsnapshot',
            name='arena_2v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_2v2', to='wowstats.PVPBracket'),
        ),
        migrations.AlterField(
            model_name='wowstatsnapshot',
            name='arena_3v3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_3v3', to='wowstats.PVPBracket'),
        ),
        migrations.AlterField(
            model_name='wowstatsnapshot',
            name='arena_rbg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_rbg', to='wowstats.PVPBracket'),
        ),
        migrations.AlterField(
            model_name='wowstatsnapshot',
            name='arena_skirmish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_skirmish', to='wowstats.PVPBracket'),
        ),
        migrations.AlterField(
            model_name='wowstatsnapshot',
            name='arena_unknown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_unknown', to='wowstats.PVPBracket'),
        ),
    ]
