# Generated by Django 2.0.2 on 2018-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0004_auto_20180819_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowcharacter',
            name='guild',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
