# Generated by Django 2.0.2 on 2018-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0005_wowcharacter_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowaccount',
            name='region',
            field=models.CharField(choices=[('eu', 'Europe'), ('us', 'United States'), ('kr', 'Korea'), ('tw', 'Taiwan'), ('sea', 'Southeast Asia')], default='eu', max_length=3),
        ),
    ]
