# Generated by Django 2.0.2 on 2018-08-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0006_auto_20180819_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wowstatsnapshot',
            name='arena_skirmish',
        ),
        migrations.RemoveField(
            model_name='wowstatsnapshot',
            name='arena_unknown',
        ),
    ]
