# Generated by Django 2.0.2 on 2018-08-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0007_auto_20180821_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wowstatsnapshot',
            options={'get_latest_by': 'snapshot_date'},
        ),
    ]
