# Generated by Django 2.0.2 on 2018-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0008_auto_20180821_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowcharacter',
            name='character_class',
            field=models.IntegerField(blank=True, choices=[(1, 'Warrior'), (2, 'Paladin'), (3, 'Hunter'), (4, 'Rogue'), (5, 'Priest'), (6, 'Death Knight'), (7, 'Shaman'), (8, 'Mage'), (9, 'Warlock'), (10, 'Monk'), (11, 'Druid'), (12, 'Demon Hunter')], null=True),
        ),
    ]
