# Generated by Django 2.0.2 on 2018-08-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0009_auto_20180821_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wowcharacter',
            old_name='character_class',
            new_name='class_id',
        ),
    ]
