# Generated by Django 2.0.2 on 2018-08-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0010_auto_20180821_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowaccount',
            name='token',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
