# Generated by Django 2.0.2 on 2018-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0011_auto_20180821_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowcharacter',
            name='race',
            field=models.IntegerField(blank=True, choices=[(1, 'Human'), (2, 'Orc'), (3, 'Dwarf'), (4, 'Night Elf'), (5, 'Undead'), (6, 'Tauren'), (7, 'Gnome'), (8, 'Troll'), (9, 'Goblin'), (10, 'Blood Elf'), (11, 'Draenei'), (12, 'Worgen'), (13, 'Pandaren'), (14, 'Pandaren'), (15, 'Pandaren'), (16, 'Nightborne'), (17, 'Highmountain Tauren'), (18, 'Void Elf'), (19, 'Lightforged Draenei'), (20, 'Dark Iron Dwarf'), (21, "Mag'har Orc")], null=True),
        ),
    ]
