# Generated by Django 2.0.2 on 2018-08-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0013_auto_20180821_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowcharacter',
            name='is_pvp',
            field=models.BooleanField(default=False),
        ),
    ]
