# Generated by Django 2.0.2 on 2018-08-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0014_wowcharacter_is_pvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowcharacter',
            name='spec',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
