# Generated by Django 2.0.2 on 2018-08-23 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0015_wowcharacter_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowstatsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 23, 9, 42, 10, 210098, tzinfo=utc)),
        ),
    ]
