# Generated by Django 2.0.2 on 2018-08-23 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wowstats', '0016_auto_20180823_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowstatsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
