# Generated by Django 2.2.8 on 2019-12-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poeactivegem',
            options={'ordering': ('name',), 'verbose_name': 'Gem', 'verbose_name_plural': 'Gems'},
        ),
        migrations.AlterModelOptions(
            name='poecharacter',
            options={'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='poeleague',
            options={'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
    ]
