# Generated by Django 2.0.2 on 2018-02-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poeleague',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poeleague',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
