# Generated by Django 2.0.2 on 2018-02-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0002_auto_20180221_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poeleague',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
