# Generated by Django 2.2.28 on 2022-11-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0003_auto_20211016_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='poecharacter',
            name='gems',
        ),
        migrations.RemoveField(
            model_name='poecharacter',
            name='league',
        ),
        migrations.RemoveField(
            model_name='poecharacter',
            name='profile',
        ),
        migrations.DeleteModel(
            name='PoeInfo',
        ),
        migrations.DeleteModel(
            name='PoeActiveGem',
        ),
        migrations.DeleteModel(
            name='PoeCharacter',
        ),
        migrations.DeleteModel(
            name='PoeLeague',
        ),
    ]
