# Generated by Django 2.0.2 on 2018-02-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0003_auto_20180221_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poeleague',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
