# Generated by Django 2.0.2 on 2018-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0004_auto_20180221_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoeInfo',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poeladder_info',
            },
        ),
    ]
