# Generated by Django 2.0.2 on 2018-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0005_poeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poecharacter',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
