# Generated by Django 2.0.2 on 2018-02-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0006_poecharacter_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poecharacter',
            old_name='ascendancy',
            new_name='class_name',
        ),
    ]
