# Generated by Django 2.0.2 on 2018-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0007_auto_20180221_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='poecharacter',
            name='ascendancy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
