# Generated by Django 2.0.2 on 2018-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0008_poecharacter_ascendancy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poeinfo',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
