# Generated by Django 2.0.2 on 2018-03-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0009_poeinfo_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoeNickname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
    ]
