# Generated by Django 2.0.2 on 2018-03-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0010_poenickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoeNickname',
        ),
    ]
