# Generated by Django 2.0.2 on 2018-05-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0011_delete_poenickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='poecharacter',
            name='experience',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poecharacter',
            name='main_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
