# Generated by Django 2.0.5 on 2018-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0011_delete_poenickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoeActiveGem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poeladder_gems',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='poecharacter',
            name='experience',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poecharacter',
            name='gems',
            field=models.ManyToManyField(to='poeladder.PoeActiveGem'),
        ),
    ]
