# Generated by Django 2.0.5 on 2018-05-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0012_auto_20180522_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poeactivegem',
            options={'ordering': ('name',), 'verbose_name_plural': 'Gems'},
        ),
        migrations.AlterModelOptions(
            name='poecharacter',
            options={'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='poeleague',
            options={'verbose_name_plural': 'Leagues'},
        ),
    ]
