# Generated by Django 2.0.2 on 2018-08-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0013_auto_20180529_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='poeleague',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
