# Generated by Django 2.0.5 on 2018-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0014_auto_20180522_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='poecharacter',
            name='skills',
            field=models.ManyToManyField(to='poeladder.PoeActiveSkill'),
        ),
        migrations.RemoveField(
            model_name='poecharacter',
            name='main_skills',
        ),
        migrations.AddField(
            model_name='poecharacter',
            name='main_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
