# Generated by Django 2.0.2 on 2018-08-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0014_poeleague_slug_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poeleague',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
