# Generated by Django 2.0.5 on 2018-05-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poeladder', '0015_auto_20180522_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poecharacter',
            name='main_skills',
        ),
    ]
