# Generated by Django 2.0.5 on 2018-05-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('poeladder', '0016_remove_poecharacter_main_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoeActiveSkill',
            new_name='PoeActiveGem',
        ),
        migrations.RenameField(
            model_name='poecharacter',
            old_name='skills',
            new_name='gems',
        ),
    ]
