# Generated by Django 2.0.5 on 2018-05-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('poeladder', '0017_auto_20180522_1548'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poeactivegem',
            table='poeladder_gems',
        ),
    ]
