# Generated by Django 2.0.2 on 2018-02-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('victims', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('actions2', models.TextField(blank=True, null=True)),
                ('places', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brawl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CachedNicknames',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cached_nicknames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gachi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'gachi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imgur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pID')),
                ('url', models.TextField(unique=True)),
                ('date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imgur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('url', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.TextField(unique=True)),
                ('steam_id', models.IntegerField(blank=True, null=True)),
                ('blizzard_id', models.TextField(blank=True, null=True)),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('mod_group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wisdom',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(db_column='pID')),
                ('text', models.TextField(unique=True)),
                ('author', models.TextField()),
                ('date', models.IntegerField()),
            ],
            options={
                'db_table': 'wisdom',
                'managed': False,
            },
        ),
    ]
