# Generated by Django 2.0.2 on 2018-02-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wisdom',
            options={},
        ),
    ]
