# Generated by Django 2.0.2 on 2018-02-20 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageApp', '0002_auto_20180219_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.TextField(unique=True)),
                ('steam_id', models.IntegerField(blank=True, null=True)),
                ('blizzard_id', models.TextField(blank=True, null=True)),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('mod_group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discord_users',
            },
        ),
        migrations.AlterModelOptions(
            name='imgur',
            options={},
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePageApp.DiscordUser', verbose_name='discord user'),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='pid',
            field=models.IntegerField(db_column='pID', default=0),
        ),
    ]
