# Generated by Django 2.0.2 on 2018-02-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageApp', '0003_auto_20180220_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgur',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imgur',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
