# Generated by Django 2.0.2 on 2018-02-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageApp', '0004_auto_20180220_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='display_name',
            field=models.TextField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.TextField(blank=True, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
