# Generated by Django 2.0.2 on 2018-02-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageApp', '0005_auto_20180220_0451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imgur',
        ),
        migrations.RemoveField(
            model_name='wisdom',
            name='author',
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
        migrations.DeleteModel(
            name='Wisdom',
        ),
    ]
