# Generated by Django 2.2.28 on 2023-02-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20221124_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
        migrations.DeleteModel(
            name='Mailbox',
        ),
    ]
